#!/bin/bash

if [ $1 ]
then

gcc sol1.c -o pa1


./pa1 < "$1" > formula.txt

z3 formula.txt > raw_data

gcc parsing1.c -o parsing

./parsing < raw_data > output.txt

mkdir -p result
mv formula.txt result
mv pa1 result
mv parsing result

rm raw_data

cat output.txt

echo "complete processing!!"

else
	echo "need input file!!"
fi
